export default [
    {
        name: "",
        href: "../../",
        icon: "fa-brands fa-twitter",
        hrefName: "",
        key: "twitter",
    },
    {
        name: "Home",
        href: "/tuiter/tuiterHome",
        icon: "fa-solid fa-house-chimney",
        hrefName: "tuiterHome",
        key: "home",
    },
    {
        name: "Explore",
        href: "/tuiter/exploreScreen",
        icon: "fa-solid fa-hashtag",
        hrefName: "exploreScreen",
        key: "explore",
    }, {
        name: "Labs",
        href: "../../",
        icon: "fa-solid fa-flask",
        key: "labs",
    },
    {
        name: "Notifications",
        href: "#",
        icon: "fa-solid fa-bell",
        key: "notifications",
    },
    {
        name: "Messages",
        href: "#",
        icon: "fa-solid fa-envelope",
        key: "messages",
    },
    {
        name: "Bookmarks",
        href: "#",
        icon: "fa-solid fa-bookmark",
        key: "bookmarks",
    },
    {
        name: "Lists",
        href: "#",
        icon: "fa-solid fa-list",
        key: "lists",
    },
    {
        name: "Profile",
        href: "/tuiter/profile",
        icon: "fa-solid fa-user",
        hrefName: "profile",
        key: "profile",
    },
    {
        name: "More",
        href: "#",
        icon: "fa-solid fa-ellipsis",
        key: "more",
    },
];
